CREATE DATABASE QuanLyKinhDoanh
GO

USE QuanLyKinhDoanh
GO

SET DATEFORMAT DMY

CREATE TABLE PHIEUBANHANG(
	SoPhieuBanHang NVARCHAR(10) PRIMARY KEY,
	NgayLap	SMALLDATETIME,
	KhachHang NVARCHAR(100),
	TongTien INT 
)

CREATE TABLE CT_PBH(
	MaCT_PBH NVARCHAR(10) PRIMARY KEY,
	SoPhieuBanHang NVARCHAR(10),
	MaSanPham NVARCHAR(10),
	SoLuong INT,
	DonGiaBanRa INT,
	ThanhTien INT 
)

CREATE TABLE SANPHAM(
	MaSanPham NVARCHAR(10) PRIMARY KEY,
	TenSanPham NVARCHAR(100),
	MaLoaiSanPham NVARCHAR(10),
	DonGiaMuaVao INT,
	SoLuongTon INT,
	DonGiaBanRa INT
)
ALTER TABLE dbo.CT_PBH ADD FOREIGN KEY(SoPhieuBanHang) REFERENCES dbo.PHIEUBANHANG(SoPhieuBanHang)
ALTER TABLE dbo.CT_PBH ADD FOREIGN KEY(MaSanPham) REFERENCES dbo.SANPHAM(MaSanPham)

CREATE TABLE LOAISANPHAM(
	MaLoaiSanPham NVARCHAR(10) PRIMARY KEY,
	TenLoaiSanPham NVARCHAR(100),
	PhanTramLoiNhuan FLOAT,
	MaDonViTinh NVARCHAR(10) 
)
ALTER TABLE dbo.SANPHAM ADD FOREIGN KEY(MaLoaiSanPham) REFERENCES dbo.LOAISANPHAM(MaLoaiSanPham)

CREATE TABLE DONVITINH(
	MaDonViTinh NVARCHAR(10) PRIMARY KEY,
	TenDonViTinh NVARCHAR(100)
)
ALTER TABLE dbo.LOAISANPHAM ADD	FOREIGN KEY(MaDonViTinh) REFERENCES dbo.DONVITINH(MaDonViTinh)

CREATE TABLE PHIEUMUAHANG(
	SoPhieuMuaHang NVARCHAR(10) PRIMARY KEY,
	NgayLap SMALLDATETIME,
	MaNhaCungCap NVARCHAR(10) ,
	TongTien INT
)

CREATE TABLE CT_PMH(
	MaCT_PMH NVARCHAR(10) PRIMARY KEY,
	SoPhieuMuaHang NVARCHAR(10) FOREIGN KEY REFERENCES dbo.PHIEUMUAHANG(SoPhieuMuaHang),
	MaSanPham NVARCHAR(10) FOREIGN KEY REFERENCES dbo.SANPHAM(MaSanPham),
	SoLuong INT,
	DonGiaMuaVao INT,
	ThanhTien INT 
)

CREATE TABLE NHACUNGCAP(
	MaNhaCungCap NVARCHAR(10) PRIMARY KEY,
	TenNhaCungCap NVARCHAR(100),
	DiaChi NVARCHAR(100),
	SoDienThoai NVARCHAR(10) 
)
ALTER TABLE dbo.PHIEUMUAHANG ADD FOREIGN KEY(MaNhaCungCap) REFERENCES dbo.NHACUNGCAP(MaNhaCungCap)

CREATE TABLE PHIEUDICHVU(
	SoPhieuDichVu NVARCHAR(10) PRIMARY KEY,
	NgayLap SMALLDATETIME,
	KhachHang NVARCHAR(100),
	SoDienThoai NVARCHAR(10),
	TongTien INT,
	TongTraTruoc INT,
	TongConLai INT,
	TinhTrang INT DEFAULT 0 --1: Hoan Thanh || 0: Chua Hoan Thanh
)

CREATE TABLE CT_PDV(
	MaCT_PDV NVARCHAR(10) PRIMARY KEY,
	SoPhieuDichVu NVARCHAR(10) FOREIGN KEY REFERENCES dbo.PHIEUDICHVU(SoPhieuDichVu),
	MaLoaiDichVu NVARCHAR(10),
	-- CONSTRAINT PK_CT_PDV PRIMARY KEY (SoPhieuDichVu,MaLoaiDichVu),
	DonGia INT,
	DonGiaDuocTinh INT,
	SoLuong INT,
	ThanhTien INT,
	TraTruoc INT,
	ConLai INT,
	NgayGiao SMALLDATETIME,
	TinhTrang INT  DEFAULT 0 --1: Da Giao || 0: Chua Giao
)

CREATE TABLE LOAIDICHVU(
	MaLoaiDichVu NVARCHAR(10) PRIMARY KEY,
	TenLoaiDichVu NVARCHAR(100),
	DonGia INT 
)
ALTER TABLE dbo.CT_PDV ADD FOREIGN KEY(MaLoaiDichVu) REFERENCES dbo.LOAIDICHVU(MaLoaiDichVu)

CREATE TABLE BAOCAOTONKHO(
	MaBaoCao NVARCHAR(10) PRIMARY KEY,
	Thang SMALLDATETIME,
	Nam SMALLDATETIME,
	MaSanPham NVARCHAR(10)  FOREIGN KEY REFERENCES dbo.SANPHAM(MaSanPham),
	MaDonViTinh NVARCHAR(10)  FOREIGN KEY REFERENCES dbo.DONVITINH(MaDonViTinh),
	TonDau INT,
	TonCuoi INT,
	SoLuongMuaVao INT,
	SoLuongBanRa INT 
)

CREATE TABLE [dbo].[NHANVIEN](
	[Manv] [nvarchar](10) PRIMARY KEY,
	[Hoten] [nvarchar](50) NOT NULL,
	[Matkhau] [nvarchar](10) NOT NULL
)

INSERT INTO dbo.NHANVIEN VALUES ('NV001','admin','1')

--Xoá 1 CT_PBH
CREATE TRIGGER tr_XoaCT_PBH ON dbo.CT_PBH FOR DELETE AS
UPDATE dbo.SANPHAM SET SoLuongTon = SoLuongTon + del.SoLuong
FROM dbo.SANPHAM INNER JOIN	Deleted del ON del.MaSanPham = SANPHAM.MaSanPham
GO
--Thêm 1 CT_PBH
CREATE TRIGGER tr_ThemCT_PBH ON dbo.CT_PBH FOR INSERT AS
UPDATE dbo.SANPHAM SET SoLuongTon = SoLuongTon - ins.SoLuong
FROM dbo.SANPHAM INNER JOIN	Inserted ins ON ins.MaSanPham = SANPHAM.MaSanPham
GO
--Sửa 1 CT_PBH
Create Trigger tr_SuaCT_PBH On CT_PBH For Update As
	DECLARE @D int
	SELECT @D = Count(*)
	FROM dbo.SANPHAM a, DELETED b, INSERTED c
	WHERE a.MaSanPham = b.MaSanPham And a.MaSanPham = c.MaSanPham
	AND a.SoLuongTon + b.SoLuong - c.SoLuong < 0
	IF (@D > 0 )
	BEGIN
		UPDATE dbo.SANPHAM SET SoLuongTon = SoLuongTon + b.SoLuong - c.SoLuong
		FROM dbo.SANPHAM a, DELETED b, INSERTED c
		WHERE a.MaSanPham = b.MaSanPham And a.MaSanPham = c.MaSanPham
	END 
GO

--Xoá 1 CT_PMH
CREATE TRIGGER tr_XoaCT_PMH ON dbo.CT_PMH FOR DELETE AS
UPDATE dbo.SANPHAM SET SoLuongTon = SoLuongTon - del.SoLuong
FROM dbo.SANPHAM INNER JOIN	Deleted del ON del.MaSanPham = SANPHAM.MaSanPham
GO
--Thêm 1 CT_PMH
CREATE TRIGGER tr_ThemCT_PMH ON dbo.CT_PMH FOR INSERT AS
UPDATE dbo.SANPHAM SET SoLuongTon = SoLuongTon + ins.SoLuong
FROM dbo.SANPHAM INNER JOIN	Inserted ins ON ins.MaSanPham = SANPHAM.MaSanPham
GO
--Sửa 1 CT_PMH
Create Trigger tr_SuaCT_PMH On CT_PMH For Update As
	DECLARE @E int
	SELECT @E = Count(*)
	FROM dbo.SANPHAM a, DELETED b, INSERTED c
	WHERE a.MaSanPham = b.MaSanPham And a.MaSanPham = c.MaSanPham
	AND a.SoLuongTon - b.SoLuong + c.SoLuong < 0
	IF (@E > 0 )
	BEGIN
		UPDATE dbo.SANPHAM SET SoLuongTon = SoLuongTon - b.SoLuong + c.SoLuong
		FROM dbo.SANPHAM a, DELETED b, INSERTED c
		WHERE a.MaSanPham = b.MaSanPham And a.MaSanPham = c.MaSanPham
	END 
GO

--CREATE TRIGGER tr_sl_CTPBH ON dbo.CT_PBH FOR INSERT AS
--BEGIN 
--	IF (SELECT COUNT(*) FROM dbo.SANPHAM sp, Inserted I
--		WHERE sp.MaSanPham = I.MaSanPham AND sp.SoLuongTon < I.SoLuong) > 0
--		BEGIN
--			PRINT 'ERROR: So luong mua phai nho hon So luong ton!'
--			ROLLBACK TRAN
--		END 
--	ELSE
--        BEGIN
--			PRINT 'Da them thanh cong!'
--		END
--END